INFO  2022-11-18 17:00:16,699 minitest.py _miniSetUp      279 =========Current case: test_01_home_page_path=========
INFO  2022-11-18 17:00:16,700 minitest.py _miniSetUp      280 package info: D:.E护通.自动化.miniapp_auto.case.homepage_test, case info: HomePageTest.test_01_home_page_path
INFO  2022-11-18 17:00:16,703 basenative.py wrapper         23  call BaseNative.back_to_miniprogram
INFO  2022-11-18 17:00:16,704 basenative.py back_to_miniprogram 528 try back_to_miniprogram 3
INFO  2022-11-18 17:00:16,705 basenative.py wrapper         27  call BaseNative.back_to_miniprogram end
INFO  2022-11-18 17:00:16,705 app.py     relaunch        387 ReLaunch: /pages/user/userindex
DEBUG 2022-11-18 17:00:16,707 connection.py send_async      211 ASYNC_SEND > {"id": "5c250aae-a366-419b-953d-fedc9f185bfe", "method": "App.callWxMethod", "params": {"method": "reLaunch", "args": [{"url": "/pages/user/userindex"}]}}
DEBUG 2022-11-18 17:00:16,807 connection.py _on_message     252 RECV < {"id":"5c250aae-a366-419b-953d-fedc9f185bfe","result":{"result":{"errMsg":"reLaunch:ok"}}}
INFO  2022-11-18 17:00:16,808 connection.py _on_message     273 received async msg: 5c250aae-a366-419b-953d-fedc9f185bfe
DEBUG 2022-11-18 17:00:17,260 connection.py _on_message     252 RECV < {"method":"App.bindingCalled","params":{"name":"onAppRouteDone","args":[{"webviewId":4,"path":"pages/user/userindex","query":{},"openType":"reLaunch","__ts__":1668762017258},1668762017259]}}
INFO  2022-11-18 17:00:17,262 app.py     _on_route_changed 588 Route changed, {'name': 'onAppRouteDone', 'args': [{'webviewId': 4, 'path': 'pages/user/userindex', 'query': {}, 'openType': 'reLaunch', '__ts__': 1668762017258}, 1668762017259]}
INFO  2022-11-18 17:00:17,265 minitest.py capture         575 capture setup.png
INFO  2022-11-18 17:00:17,266 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:00:17,266 connection.py send            201 SEND > {"id":"227b294f-871f-4915-b069-eba0e57e69a5","method":"App.captureScreenshot","params":{}}
INFO  2022-11-18 17:01:17,431 minitest.py capture         575 capture setup.png
INFO  2022-11-18 17:01:17,431 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:01:17,431 connection.py send            201 SEND > {"id":"8a2eb347-159d-4b24-910f-899951493f3b","method":"App.captureScreenshot","params":{}}
DEBUG 2022-11-18 17:02:17,607 minitest.py _miniTearDown   513 =========Current case Down: test_01_home_page_path=========
INFO  2022-11-18 17:02:17,608 minitest.py capture         575 capture teardown.png
INFO  2022-11-18 17:02:17,608 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:02:17,608 connection.py send            201 SEND > {"id":"aaea275b-cac6-49c3-9087-d4b39933b8bd","method":"App.captureScreenshot","params":{}}
INFO  2022-11-18 17:03:17,791 minitest.py capture         575 capture teardown.png
INFO  2022-11-18 17:03:17,792 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:03:17,792 connection.py send            201 SEND > {"id":"82f0db4b-ef76-45f0-9c5a-4c001d01b9b9","method":"App.captureScreenshot","params":{}}
ERROR 2022-11-18 17:04:17,967 minitest.py _miniTearDown   532 [call App.captureScreenshot] receive from remote timeout, id: 82f0db4b-ef76-45f0-9c5a-4c001d01b9b9
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 521, in _miniTearDown
    retry(2)(self.capture)("teardown")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\utils\utils.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 576, in capture
    self.native.screen_shot(path)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\basenative.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\idenative.py", line 70, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\app.py", line 179, in screen_shot
    self.connection.send("App.captureScreenshot")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 203, in send
    return self._receive_response(cmd)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 230, in _receive_response
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: [call App.captureScreenshot] receive from remote timeout, id: 82f0db4b-ef76-45f0-9c5a-4c001d01b9b9
ERROR 2022-11-18 17:04:18,009 assertbase.py _teardown_collect 273 <bound method HomePageTest.test_01_home_page_path of <case.homepage_test.HomePageTest testMethod=test_01_home_page_path>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\libs\unittest\case.py", line 37, in testPartExecutor
    yield
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\libs\unittest\case.py", line 114, in run
    self._miniSetUp()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 349, in _miniSetUp
    retry(2)(self.capture)("setup")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\utils\utils.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 576, in capture
    self.native.screen_shot(path)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\basenative.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\idenative.py", line 70, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\app.py", line 179, in screen_shot
    self.connection.send("App.captureScreenshot")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 203, in send
    return self._receive_response(cmd)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 230, in _receive_response
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: [call App.captureScreenshot] receive from remote timeout, id: 8a2eb347-159d-4b24-910f-899951493f3b
